version: "3.9"

services:
  sglang-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.gh200
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    container_name: sglang-dev
    command: sleep infinity
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    working_dir: /workspaces/sglang
    tty: true
    stdin_open: true
    gpus: all
    shm_size: 32g
    ipc: host
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      HOME: /home/devuser
      CUDA_HOME: /usr/local/cuda
      TRITON_CACHE_DIR: /profiles/triton
      TORCHINDUCTOR_CACHE_DIR: /profiles/torchinductor
      FLASHINFER_WORKSPACE_DIR: /profiles/flashinfer
      PROMETHEUS_MULTIPROC_DIR: /profiles/prom/tmp
    volumes:
      - ..:/workspaces/sglang
      - ../.devcontainer/storage/models:/models
      - ../.devcontainer/storage/huggingface:/home/devuser/.cache/huggingface
      - ../.devcontainer/storage/profiles:/profiles
    ports:
      - "30000:30000"
      - "29000:29000"

  jaeger:
    profiles: ["observability"]
    image: jaegertracing/all-in-one:1.57
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"

  otel-collector:
    profiles: ["observability"]
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    command: ["--config", "/etc/otelcol/config.yaml"]
    volumes:
      - ../.devcontainer/observability/otel-collector.yml:/etc/otelcol/config.yaml:ro
    depends_on:
      - jaeger

  prometheus:
    profiles: ["observability"]
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"
    volumes:
      - ../.devcontainer/observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
